### ISSUE TITLE
There is no 1. 初始化DB，添加配置 导入db/cassie_admin.sql

### ISSUE THREAD

**Issue by makorne** [Cassielxd/cassie_axum#2]
Looks cassie_admin.sql is missed 
Please add it.

**Comment by Cassielxd** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Cassielxd/cassie_axum"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月23日(星期四) 下午2:03
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Cassielxd/cassie_axum] There is no 1. 初始化DB，添加配置 导入db/cassie_admin.sql (Issue #2)





 
Looks cassie_admin.sql is missed
 Please add it.

**Comment by Cassielxd** [comment]
![image](https://user-images.githubusercontent.com/34414950/227190493-e0c44e4d-da4c-4255-afe3-71ebf164b078.png)

**Comment by Cassielxd** [comment]
under the list of content ,  you can have a look

https://github.com/Cassielxd/cassie_axum/blob/master/cassie_admin.sql

**Comment by makorne** [comment]
Thank you!!!!
